version: "3.9"
services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "su.scrt.pwd"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pbuser -d phonedb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G